version = 1

exclude_patterns = [
  "/Assets/Scripts/EVA/**/!(*.cs)",
  "/Assets/Scripts/!(EVA)/**/*",
  "/Assets/!(Scripts)/**/*",
  "/!(Assets)/**/*",
  "/!(Assets)"
]

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"